### ISSUE TITLE
Observed #375 in 1.5.8

### ISSUE THREAD

**Issue by polarG** [splunk/splunk-connect-for-snmp#422]
Observed #375 in 1.5.8

[2022-03-02 18:50:46,344: ERROR/ForkPoolWorker-1] Task splunk_connect_for_snmp.snmp.tasks.poll[121f1930-52bf-46d8-b353-fb962e78d568] raised unexpected: SnmpActionError('An error of SNMP isWalk=False for a host 10.224.122.67 occurred: No SNMP response received before timeout')
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/tasks.py", line 110, in poll
    _, result = self.do_work(ir, profiles=profiles)
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/manager.py", line 335, in do_work
    if not _any_failure_happened(
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/manager.py", line 117, in _any_failure_happened
    raise SnmpActionError(
splunk_connect_for_snmp.snmp.exceptions.SnmpActionError: An error of SNMP isWalk=False for a host 10.224.122.67 occurred: No SNMP response received before timeout
[2022-03-02 18:50:48,880: ERROR/ForkPoolWorker-2] Task splunk_connect_for_snmp.snmp.tasks.poll[3550f995-b174-46e3-8d1c-64b145c5e258] raised unexpected: MongoLockLocked('Timeout, lock owned by 45769e19-c27c-43e2-a783-8f2917d35040 since 2022-03-02 18:50:46.350000, expire time is 2022-03-02 18:52:16.347000')
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/tasks.py", line 108, in poll
    with lock(kwargs["address"], self.request.id, expire=90, timeout=20):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/app/.venv/lib/python3.10/site-packages/mongolock.py", line 45, in __call__
    raise MongoLockLocked(
mongolock.MongoLockLocked: Timeout, lock owned by 45769e19-c27c-43e2-a783-8f2917d35040 since 2022-03-02 18:50:46.350000, expire time is 2022-03-02 18:52:16.347000
[2022-03-02 18:50:52,366: ERROR/ForkPoolWorker-1] Task splunk_connect_for_snmp.snmp.tasks.poll[45769e19-c27c-43e2-a783-8f2917d35040] raised unexpected: SnmpActionError('An error of SNMP isWalk=False for a host 10.224.122.67 occurred: No SNMP response received before timeout')
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/tasks.py", line 110, in poll
    _, result = self.do_work(ir, profiles=profiles)
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/manager.py", line 335, in do_work
    if not _any_failure_happened(
  File "/app/.venv/lib/python3.10/site-packages/splunk_connect_for_snmp/snmp/manager.py", line 117, in _any_failure_happened
    raise SnmpActionError(
splunk_connect_for_snmp.snmp.exceptions.SnmpActionError: An error of SNMP isWalk=False for a host 10.224.122.67 occurred: No SNMP response received before timeout

**Comment by polarG** [comment]
I fixed this by extend the default udp timeout to 3, i think the default is 1.
Configuration changes:  value.worker.udpConnectionTimeout = 3.

The UDP timeout depends on customer's network condition. So for the default value, it must can handle the worst network environment. It's better to extend the default value.

From the log side, assertion is not a good choice.
